[project]
name = "datamart_scripts"
version = "0.1.0"
dependencies = [
  "pandas",
  "requests",
  "psycopg2",
  "sqlalchemy",
  "numpy",
  "openpyxl",
  "icecream",
  "xlsxwriter>=3.2.5",
  "tqdm>=4.67.1",
]
